spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.239.151:31500
        file-extension: yaml
      discovery:
        server-addr: 192.168.239.151:31500
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.239.151:30002/db02?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
seata:
  config:
    type: nacos
    nacos:
      server-addr: 192.168.239.151:31500
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.239.151:31500
      group: SEATA_GROUP
      namespace: ""
      cluster: default
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default
  data-source-proxy-mode: XA
upload:
  dir: D:/petbook/