spring:
  cloud:
    loadbalancer:
      service-discovery:
        timeout: 5000
    nacos:
      config:
        server-addr: nacos-headless.petbook:8848
        file-extension: yaml
      discovery:
        server-addr: nacos-headless.petbook:8848