spring:
  redis:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    sentinel:
      # 主节点的别名
      master: mymaster
      # sentinel服务的ip和端口
      nodes: redis-node-0.redis-headless.petbook.svc.cluster.local:26379,redis-node-1.redis-headless.petbook.svc.cluster.local:26379,redis-node-2.redis-headless.petbook.svc.cluster.local:26379
      password: mingyi

  rabbitmq:
    port: 5672
    host: rabbitmq.petbook
    username: mingyi
    password: mingyi
    publisher-confirm-type: correlated
socketio:
  host: 0.0.0.0
  port: 8888
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

serverId: ${SERVER_ID}
chatQueue: "CHAT_QUEUE${serverId}"
serviceQueue: "SERVICE_QUEUE${serverId}"
systemQueue: "SYSTEM_QUEUE${serverId}"
