spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-write.petbook:3306/user_base?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
seata:
  config:
    type: nacos
    nacos:
      server-addr: nacos-headless.petbook:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server-k8s
      server-addr: nacos-headless.petbook:8848
      group: SEATA_GROUP
      namespace: ""
      cluster: default
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default
  data-source-proxy-mode: AT