kind: Service
apiVersion: v1
metadata:
  name: pet-service-consumer
  namespace: petbook
  labels:
    app: pet-service-consumer
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pet-service-consumer
  type: ClusterIP
  sessionAffinity: None
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: pet-service-consumer
  namespace: petbook
  labels:
    app: pet-service-consumer
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-service-consumer
      version: v1
  template:
    metadata:
      labels:
        app: pet-service-consumer
        version: v1
    spec:

      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/pet-service-consumer:latest
          name: pet-service-consumer
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
