spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-write.petbook:3306/db02?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis-master.petbook
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    password: mingyi

  rabbitmq:
    port: 5672
    host: rabbitmq.petbook
    username: mingyi
    password: mingyi
    publisher-confirm-type: correlated
#seata:
#  config:
#    type: nacos
#    nacos:
#      server-addr: nacos-headless.petbook:8848
#      group: SEATA_GROUP
#      data-id: seataServer.properties
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server-k8s
#      server-addr: nacos-headless.petbook:8848
#      group: SEATA_GROUP
#      namespace: ""
#      cluster: default
#  tx-service-group: mygroup
#  service:
#    vgroup-mapping:
#      mygroup: default
#  data-source-proxy-mode: XA