seata:
  config:
    type: nacos
    nacos:
      server-addr: nacos-headless.petbook:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server-k8s
      server-addr: nacos-headless.petbook:8848
      group: SEATA_GROUP
      namespace: ""
      cluster: default
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default
  data-source-proxy-mode: AT