kind: Service
apiVersion: v1
metadata:
  name: interaction-service-consumer
  namespace: petbook
  labels:
    app: interaction-service-consumer
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: interaction-service-consumer
  type: ClusterIP
  sessionAffinity: None
