spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-write.petbook:3306/db02?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    sentinel:
      # 主节点的别名
      master: mymaster
      # sentinel服务的ip和端口
      nodes: redis-node-0.redis-headless.petbook.svc.cluster.local:26379,redis-node-1.redis-headless.petbook.svc.cluster.local:26379,redis-node-2.redis-headless.petbook.svc.cluster.local:26379
      password: mingyi
